backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "katalog"
    label: "Katalog"
    folder: "content/katalog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Açıklama", name: "description", widget: "text", required: false}
      - {label: "Görsel", name: "image", widget: "image"}
      
media_folder: "images" # Veya senin görselleri kaydettiğin klasör adı (örn: "assets/images" veya "uploads")
public_folder: "/images" # media_folder'ın başındaki slash (/) ile birlikte tam yolu
